# Generated by Django 5.0.7 on 2024-08-05 12:09

import base.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('config', models.FileField(blank=True, null=True, upload_to=base.models.custom_qn_config_upload_to)),
                ('src_files_zip', models.FileField(blank=True, null=True, upload_to=base.models.custom_qn_src_upload_to)),
                ('test', models.FileField(blank=True, null=True, upload_to=base.models.custom_qn_test_upload_to)),
                ('docker_image', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
